# config.yaml

# === SERIAL PORT SETTINGS ===
serial:
  port: "COM3"
  baud_rate: 500000

# === AUDIO / SAMPLING SETTINGS ===
audio:
  sample_rate: 22050
  block_size: 512
  window_duration: 2.0      # seconds
  step_duration: 1.0        # seconds

# === WINDOW CALCULATED ===
window:
  size: 44100               # sample_rate * window_duration
  step: 22050               # sample_rate * step_duration

# === LOGGING SETTINGS ===
logging:
  log_dir: "log"
  rotation_minutes: 3

# === COMPONENT NAMES ===
components:
  - mast
  - elevator
  - gripper
  - shuttle
  - environment

# === MODEL PATHS ===
models:
  ocsvm: "model_file/ocsvm_model.joblib"
  log_reg: "model_file/log_reg_model.joblib"
  scaler: "model_file/scaler.joblib"

testers:
  name: "IPC1"
